spring:
  application:
    name: translation-bot
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_ADDRESS:localhost}:${DB_PORT:5432}/${DB_NAME:sellauto}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:admin}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show.sql: true
        format_sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      enabled: true
  mail:
    host: smtp.yandex.ru
    protocol: smtp
    port=: 465
    username: ${YANDEX_EMAIL_USERNAME:freelance.bot@yandex.ru}
    password: ${YANDEX_EMAIL_PASSWORD:nphbbwxbflkheahk}
    properties:
      mail:
        smtp:
          enable: true
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            fallback: true
springdoc:
  api-docs:
    path: /v3/api-docs
server:
  port: ${PORT:8082}

ad:
  photo:
    directory: photos

logging:
  level:
    org:
      springframework:
        security: info
        messaging: info
    ru:
      eddyz:
        sellautorestapi:
          config:
            JwtWebSocketInterceptor: info
    web: info
    root: info
jwt:
  secret: nMwHOhTGsd7R6kCWcrfNC4FC/vguVFd6gI4lScbapVU=
  issuer: sellauto



