spring:
  application:
    name: translation-bot
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_ADDRESS:localhost}:${DB_PORT:5432}/${DB_NAME:sellauto}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:admin}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show.sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      enabled: true
server:
  port: ${PORT:8082}

ad:
  photo:
    directory: photos

logging:
  level:
    org:
      springframework:
        security: DEBUG
jwt:
  secret: nMwHOhTGsd7R6kCWcrfNC4FC/vguVFd6gI4lScbapVU=
  issuer: sellauto

